# alembic/versions/0002_reading_partitions.py
from __future__ import annotations

from alembic import op

revision = "0002_reading_partitions"
down_revision = "0001_init"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Если таблица reading уже есть от 0001 — дропаем (данных пока нет, судя по старту)
    op.execute("DROP TABLE IF EXISTS reading CASCADE;")

    # Партиционированная таблица: ВАЖНО — без PRIMARY KEY/UNIQUE на родителе (из-за RANGE(ts))
    op.execute(
        """
        CREATE TABLE reading (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            parameter_id INTEGER NOT NULL REFERENCES parameter(id) ON DELETE CASCADE,
            ts TIMESTAMPTZ NOT NULL,

            trigger VARCHAR(32),
            status_source VARCHAR(32),
            status_code INTEGER,
            status_message TEXT,
            silent_for_s INTEGER,

            value_num DOUBLE PRECISION,
            value_text TEXT,
            raw JSONB
        ) PARTITION BY RANGE (ts);
        """
    )

    # Индексы: критичные
    op.execute("CREATE INDEX IF NOT EXISTS ix_reading_param_ts_desc ON reading (parameter_id, ts DESC);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_reading_ts_desc ON reading (ts DESC);")

    # Функция создания партиций (idempotent)
    op.execute(
        """
        CREATE OR REPLACE FUNCTION create_reading_partition(dt_from DATE, dt_to DATE)
        RETURNS void
        LANGUAGE plpgsql
        AS $$
        DECLARE
            part_name TEXT := 'reading_' || to_char(dt_from, 'YYYY_MM');
        BEGIN
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS %I PARTITION OF reading FOR VALUES FROM (%L) TO (%L);',
                part_name, dt_from::timestamptz, dt_to::timestamptz
            );
            EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I (parameter_id, ts DESC);', part_name || '_p_ts', part_name);
            EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I (ts DESC);', part_name || '_ts', part_name);
        END $$;
        """
    )

    # Создаём партиции: прошлый/текущий/следующий месяц
    op.execute(
        """
        SELECT create_reading_partition(
            (date_trunc('month', now()) - interval '1 month')::date,
            (date_trunc('month', now()))::date
        );
        SELECT create_reading_partition(
            (date_trunc('month', now()))::date,
            (date_trunc('month', now()) + interval '1 month')::date
        );
        SELECT create_reading_partition(
            (date_trunc('month', now()) + interval '1 month')::date,
            (date_trunc('month', now()) + interval '2 month')::date
        );
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS reading CASCADE;")
    op.execute("DROP FUNCTION IF EXISTS create_reading_partition(DATE, DATE);")

    # Вернём обычную таблицу (как было в 0001) — тоже без PK можно, но оставим просто так:
    op.execute(
        """
        CREATE TABLE reading (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            parameter_id INTEGER NOT NULL REFERENCES parameter(id) ON DELETE CASCADE,
            ts TIMESTAMPTZ NOT NULL,

            trigger VARCHAR(32),
            status_source VARCHAR(32),
            status_code INTEGER,
            status_message TEXT,
            silent_for_s INTEGER,

            value_num DOUBLE PRECISION,
            value_text TEXT,
            raw JSONB
        );
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_reading_param_ts_desc ON reading (parameter_id, ts DESC);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_reading_ts_desc ON reading (ts DESC);")
